.TH GROUPWAREWIZARD 1
.SH NAME
groupwarewizard \- KDE Groupware Wizard
.SH SYNOPSIS
.B groupwarewizard
.I [Qt-options] [KDE-options] [options]
.SH DESCRIPTION
.B groupwarewizard
is a front end to configure eGroupware, Kolab, and SUSE Linux Openexchange
servers.
.SH PROGRAM OPTIONS
.TP
.B --serverType \fI<type>\fB
The server type to configure.
.so kdeopt.man
.SH SEE ALSO
.B egroupwarewizard
(1),
.B kolabwizard
(1),
.B sloxwizard
(1).

