.TH ICAL2VCAL 1
.SH NAME
ical2vcal \- Convert calendars from iCal to Versit vCal format
.SH SUMMARY
.B ical2vcal
.I [infile] outfile
.SH DESCRIPTION
.B ical2vcal
converts calendars from iCal to Versit vCal format, which is the standard
format used internally by KOrganizer.
.SH OPTIONS
.TP
.B infile
Specifies the name of the iCal calendar file to read in.
The default is ~/.calendar.
.TP
.B outfile
Specifies the name of the vCal calendar file to write.
.SH SEE ALSO
.BR korganizer (1).
