.TH KABC2MUTT 1
.SH NAME
kabc2mutt \- kabc to mutt converter
.SH SYNOPSIS
.B kmahjongg
.I [Qt-options] [KDE-options] [options]
.SH DESCRIPTION
kabc2mutt converts the KDE address book's entries to Mutt format.
.SH PROGRAM OPTIONS
.TP
.B --query \fI<substring>\fB
Only show contacts where name or address matches \fI<substring>\fP.
.TP
.B --format \fI<format>\fB
Default format is `alias'. `query' returns
email\fB<tab>\fPname\fB<tab>\fP, as needed by mutt's query_command.
.TP
.B --ignore-case
Make queries case insensitive.
.TP
.B --all-addresses
Return all mail addresses, not just the preferred one.
.so kdeopt.man
.SH SEE ALSO
.B kaddressbook
(1).
