.TH KADDRESSBOOK 1
.SH NAME
kaddressbook \- The KDE Address Book
.SH SYNOPSIS
.B kaddressbook
.I [Qt-options] [KDE-options] [options]
.SH DESCRIPTION
\fBKAddressBook\fP is the main address book application for KDE; it enables
you to manage your contacts efficiently and comfortably.  Since it is based
on the kabc library it supports resources, which can be used to load and save
your contacts to many different locations -- not just the local file system,
but also to LDAP servers and SQL databases.

The user interface is similar to MS Outlook and it supports different views
to represent the contact data differently; it also provides an incremental
search over all fields and a jump button bar to quickly access single entries.
Since the underlying kabc library uses the vCard format (specified in RFC 2426)
as its default storage medium, KAddressBook mainly reflects the supported
entry fields in its graphical user interface.
.SH PROGRAM OPTIONS
.TP
.B -a, --addr \fI<email>\fB
Shows contact editor with given email address.
.TP
.B --uid \fI<uid>\fB
Shows contact editor with given uid.
.TP
.B --editor-only
Launches in editor only mode.
.TP
.B --new-contact
Launches editor for the new contact.
.TP
.B --document \fI<file>\fB
Work on given file.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/kaddressbook
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/kaddressbook').
