.TH KALARMD 1
.SH NAME
kalarmd \- KAlarm alarm daemon
.SH SYNOPSIS
.B kalarmd
.I [Qt-options] [KDE-options] [options]
.SH DESCRIPTION
.B kalarmd
runs in the background and handles displaying the events scheduled by
\fBkalarm\fP.  You should normally not have to run this daemon manually.
.SH PROGRAM OPTIONS
.TP
.so kdeopt.man
.SH SEE ALSO
.B kalarm
(1).
