.TH KANDY 1
.SH NAME
kandy \- Synchronize mobile phone address books
.SH SYNOPSIS
.B kandy
.I [Qt-options] [KDE-options] [options] [profile]
.SH DESCRIPTION
At the moment
.B kandy
is more or less a terminal program with some special features to store
commands and their parameters, but it also has a simple GUI to access the
phone book of a mobile phone and it is able to save this phone book to the
KDE address book.

.B kandy
is aimed at mobile phones with integrate (GSM) modems.
.SH PROGRAM OPTIONS
.TP
.B --terminal
Show terminal window.
.TP
.B --mobilegui
Show mobile GUI.
.TP
.B --nogui
Do not show GUI.
.TP
.B profile
Filename of command profile file.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/kandy
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/kandy').
