.TH KANDY_CLIENT 1
.SH NAME
kandy_client \- DCOP client for Kandy
.SH SYNOPSIS
.B kandy_client
.I [Qt-options] [KDE-options] [URL]
.SH DESCRIPTION
.B kandy_client
sends a URL to a running
.B kandy
instance.
.SH PROGRAM OPTIONS
.TP
.B URL
URL to send to \fBkandy\fP.  Default is `\fIhttp://www.kde.org'\fP.
.so kdeopt.man
.SH SEE ALSO
.B kandy
(1).
