.TH KARM 1
.SH NAME
karm \- KDE time tracker tool
.SH SYNOPSIS
.B karm
.I [Qt-options] [KDE-options]
.SH DESCRIPTION
.B KArm
tracks time spent on various tasks.  It is useful for tracking billable
hours and can report the hours logged by task and day.  This time history
can be exported to a comma-delimited text file for import into other billing
and/or project management tools.

.B KArm
detects when your keyboard and mouse are idle and can associate different
tasks with different desktops, two tools that can help keep the timer
running on the correct task.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/karm
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/karm').
