.TH KLEOPATRA 1
.SH NAME
kleopatra \- KDE X.509 key manager
.SH SYNOPSIS
.B kleopatra
.I [Qt-options] [KDE-options] [options] [address|URL]
.SH DESCRIPTION
.B Kleopatra
is the KDE tool for managing X.509 certificates in the GpgSM keybox and for
retrieving certificates from LDAP servers.
.SH PROGRAM OPTIONS
.TP
.B --external
Search for external certificates initially.
.TP
.B --query
Initial query string.
.TP
.B --import-certificate
Name of certificate file to import.
.TP
.B URL
Attach the file that `URL' points to.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/kleopatra
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/kleopatra').
