.TH KMAILCVT 1
.SH NAME
kmailcvt \- KMail import filters
.SH SYNOPSIS
.B kmailcvt
.I [Qt-options] [KDE-options]
.SH DESCRIPTION
.B kmailcvt
provides a frontend to import mail folders into \fBkmail\fP.  Supported
formats include Outlook Express, mbox files, plain text, Pegasus-Mail,
and Evolution.
.so kdeopt.man
.SH SEE ALSO
.B kmail
(1).
