.TH KMAIL 1
.SH NAME
kmail \- KDE email client
.SH SYNOPSIS
.B kmail
.I [Qt-options] [KDE-options] [options] [address|URL]
.SH DESCRIPTION
.B KMail
is a fully-featured email client that fits nicely into the KDE desktop.
It has features such as support for IMAP, POP3, multiple accounts,
mail filtering and sorting, PGP/GnuPG privacy, and inline attachments.
.SH PROGRAM OPTIONS
.TP
.B -s, --subject \fI<subject>\fB
Set subject of message.
.TP
.B -c, --cc \fI<address>\fB
Send CC: to `address'.
.TP
.B -b, --bcc \fI<address>\fB
Send BCC: to `address'.
.TP
.B -h, --header \fI<header>\fB
Add `header' to message.
.TP
.B --msg \fI<file>\fB
Read message body from `file'.
.TP
.B --body \fI<text>\fB
Set body of message.
.TP
.B --attach \fI<url>\fB
Add an attachment to the mail. This can be repeated.
.TP
.B --check
Only check for new mail.
.TP
.B --composer
Only open composer window.
.TP
.B --view \fI<url>\fB
View the given message file.
.TP
.B address
Send message to `address'.
.TP
.B URL
Attach the file that `URL' points to.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/kmail
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/kmail').
