.TH KNODE 1
.SH NAME
knode \- KDE news reader
.SH SYNOPSIS
.B knode
.I [Qt-options] [KDE-options] [url]
.SH DESCRIPTION
.B KNode
is an easy-to-use, convenient newsreader; it is intended to allow even
newbies to use a newsreader under KDE, but it also offers advanced features
appealing to experienced users.
.SH PROGRAM OPTIONS
.TP
.B url
A `news://server/group' URL.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/knode
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/knode').
