.TH KNOTES 1
.SH NAME
knotes \- Sticky notes application for KDE
.SH SYNOPSIS
.B knotes
.I [Qt-options] [KDE-options]
.SH DESCRIPTION
.B KNotes
is a program that lets you write the computer equivalent of sticky notes.
The notes are saved automatically when you exit the program, and they
display when you open the program.  You may print and mail your notes if
you configure
.B KNotes
to use helper applications.

Display features of notes such as color and font may be customized for each
note.  You may also customize the defaults.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/knotes
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/knotes').
