.TH KONTACT 1
.SH NAME
kontact \- Integrated KDE personal information management application
.SH SYNOPSIS
.B kontact
.I [Qt-options] [KDE-options] [options]
.SH DESCRIPTION
.B Kontact
is the integrated solution for personal information management.  It combines
the well-known KDE applications for email, scheduling, address book, notes
and newsgroups (KMail, KOrganizer, KAddressBook, KNotes and KNode) into a
single interface.  Being based on a true component framework Kontact provides
exactly the same functionality as the stand-alone applications, and adds
more features, by making use of the integrated way Kontact runs the
applications as components.  Users still retain the choice of which
applications are run within Kontact and which are run stand-alone.
.SH PROGRAM OPTIONS
.TP
.B --module \fI<module>\fB
Start with a specific Kontact module.
.TP
.B --nosplash
Disable the splash screen.
.TP
.B --list
List all possible modules and exit.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/kontact
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/kontact').
