.TH KORGAC 1
.SH NAME
korgac \- KOrganizer alarm daemon
.SH SYNOPSIS
.B korgac
.I [Qt-options] [KDE-options]
.SH DESCRIPTION
.B korgac
runs in the background and handles displaying alarms from the KOrganizer
calendar.  It is normally started at login and displays an icon in the
Kicker system tray, but if you have disabled this
feature you may need to start korgac manually.
.so kdeopt.man
.SH SEE ALSO
.BR korganizer (1).
