.TH KORGANIZERIN 1
.SH NAME
korganizerIn \- KOrganizer event mail filter
.SH DESCRIPTION
.B korganizerIn
is a mail filter which searches for vCal events in incoming messages and,
if found, writes these events to KOrganizer's incoming queue.  You can set
up KMail to apply this filter automatically, or you can set up procmail
to pipe all incoming messages through this filter.

.B korganizerIn
takes no command line arguments.
.SH SEE ALSO
.BR korganizer (1).
