.TH KORGANIZER 1
.SH NAME
korganizer \- Personal organizer for KDE
.SH SYNOPSIS
.B korganizer
.I [Qt-options] [KDE-options] [options] [calendar]
.SH DESCRIPTION
.B KOrganizer
is a calendar application for KDE.  You can schedule appointments, events,
and to-do tasks.  KOrganizer will remind you about pending tasks, and help
you keep your schedule.  It supports event categories, highlighting
according to category, numerous options for generating repeated events,
emerging group scheduling support, PalmPilot synchronization, and much more.
.SH PROGRAM OPTIONS
.TP
.B -i, --import \fI<url>\fB
Import calendar at `url' into default calendar.
.TP
.B calendar
A calendar file to load.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/korganizer
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/korganizer').
