.TH KORN 1
.SH NAME
korn \- Sticky notes application for KDE
.SH SYNOPSIS
.B korn
.I [Qt-options] [KDE-options]
.SH DESCRIPTION
.B KOrn
is a KDE mail checker that has the capability to dock itself to Kicker.
KOrn can check mbox, qmail, POP3, and Imap4 mailboxes, as well as nntp
servers.  KOrn checks your mail on an interval that is user specified for
each separate account.  Once mail is received you can have KOrn run a
third party program of your wish or change the color/icon of KOrn while
docked in Kicker.  In addition to this you can have KOrn run a program
once you click on the docked icon in Kicker.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/korn
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/korn').
