.TH KPALMDOC 1
.SH NAME
kpalmdoc \- KDE converter for PalmDOC texts
.SH SYNOPSIS
.B kpalmdoc
.I [Qt-options] [KDE-options]
.SH DESCRIPTION
.B KPalmDOC
provides a user interface to converting between text files and PalmDOC files.
Note that KPilot can also handle these conversions internally using the
PalmDOC conduit.
.so kdeopt.man
.SH SEE ALSO
.BR kpilot (1).
