.TH KPILOT 1
.SH NAME
kpilot \- Palm Pilot synchronization software for KDE
.SH SYNOPSIS
.B kpilot
.I [Qt-options] [KDE-options] [options]
.SH DESCRIPTION
.B KPilot
is an application that synchronizes a PalmPilot or similar device with
the KDE desktop, much like the Palm Desktop HotSync software does for
Windows.  KPilot can backup, restore, and HotSync your PalmPilot.  It can
synchronize the built-in applications with their KDE counterparts.  It also
features additional conduits for third-party software.
.SH PROGRAM OPTIONS
.TP
.B -s, --setup
Setup the Pilot device, conduits and other parameters.
.TP
.B -c, --conduit-setup
Deprecated, use
.B --setup
instead.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/kpilot
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/kpilot').
