.TH KPILOTDAEMON 1
.SH NAME
kpilotDaemon \- KPilot server
.SH SYNOPSIS
.B kpilotDaemon
.I [Qt-options] [KDE-options] [options]
.SH DESCRIPTION
.B kpilotDaemon
is a program that runs in the background and handles the actual communication
with the PalmPilot device.  It is run automatically when needed, so you
normally should not have to run it manually.
.SH PROGRAM OPTIONS
.TP
.B --fail-silently
Fail instead of complaining about bad configuration files.
.so kdeopt.man
.SH SEE ALSO
.BR kpilot (1).
