.TH KTNEF 1
.SH NAME
ktnef \- TNEF file viewer
.SH SYNOPSIS
.B ktnef
.I [Qt-options] [KDE-options] [file]
.SH DESCRIPTION
.B Ktnef
is an application for to view TNEF mail attachments.  These attachments are
usually found in mails coming from Microsoft mail servers and embed the mail
properties as well as the actual attachments.
.SH PROGRAM OPTIONS
.TP
.B file
Attachment file to view.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/ktnef
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/ktnef').
