.TH KWATCHGNUPG 1
.SH NAME
kwatchgnupg \- GnuPG log viewer
.SH SYNOPSIS
.B kwatchgnupg
.I [Qt-options] [KDE-options]
.SH DESCRIPTION
.B KWatchGnuPG
is a simple GnuPG log viewer for GnuPG.  It works as a GUI wrapper around
the command line tool \fBwatchgnupg\fP, which listens on a socket for log lines
from the GnuPG backend applications.
.so kdeopt.man
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/kwatchgnupg
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/kwatchgnupg').
