/*
 * This file was generated by dbusidl2cpp version 0.4
 * when processing input file foo.xmi
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef FOO_CPP_68451148753567
#define FOO_CPP_68451148753567

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <dbus/qdbus.h>

/*
 * Proxy class for interface local.Akonadi.Resources
 */
class LocalAkonadiResourcesInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "local.Akonadi.Resources"; }

public:
    explicit LocalAkonadiResourcesInterface(QDBusAbstractInterfacePrivate *p);

    ~LocalAkonadiResourcesInterface();

public Q_SLOTS: // METHODS
    inline QDBusReply<QStringList> listAvailableResources()
    {
        return call(QLatin1String("listAvailableResources"));
    }

Q_SIGNALS: // SIGNALS
};

namespace local {
  namespace Akonadi {
    typedef ::LocalAkonadiResourcesInterface Resources;
  }
}
#endif
/*
 * Implementation of interface class LocalAkonadiResourcesInterface
 */

LocalAkonadiResourcesInterface::LocalAkonadiResourcesInterface(QDBusAbstractInterfacePrivate *p)
    : QDBusAbstractInterface(p)
{
}

LocalAkonadiResourcesInterface::~LocalAkonadiResourcesInterface()
{
}

