#ifndef __KMIME_VERSION_H__
#define __KMIME_VERSION_H__

#define KMIME_MAJOR 0;
#define KMIME_MINOR 1;
#define KMIME_PATCHLEVEL 0;
#define KMIME_VERSION (KMIME_MAJOR * 100 + KMIME_MINOR * 10 + KMIME_PATCHLEVEL)
#define KMIME_VERSION_STRING "0.1.0"

#endif // __KMIME_VERSION_H__
