/*
* ecfg.h -- Declaration of class KExternCfg.
* Generated by newclass on Sat Nov 21 18:50:13 EST 1998.
*/
#ifndef SSK_ECFG_H
#define SSK_ECFG_H

#include "moncfg.h"

class QLineEdit;
class KExternDrop;

/**
* @short KExternCfg
* @author Sirtaj Singh Kang (taj@kde.org)
* @version $Id$
*/
class KExternCfg : public KMonitorCfg
{
	Q_OBJECT
public:
	/**
	* KExternCfg Constructor
	*/
	KExternCfg( KExternDrop * );

	/**
	* KExternCfg Destructor
	*/
	virtual ~KExternCfg() {}
	
	virtual QString name() const;
	virtual QWidget *makeWidget( QWidget *parent );
	virtual void updateConfig();
	
private:
	KExternCfg& operator=( const KExternCfg& );
	KExternCfg( const KExternCfg& );

	QLineEdit *_cmdEdit;
};

#endif // SSK_ECFG_H
