/*
* gencfg.h -- Declaration of class KGeneralCfg.
* Generated by newclass on Mon Aug  3 01:32:26 EST 1998.
*/
#ifndef SSK_GENCFG_H
#define SSK_GENCFG_H

#include"moncfg.h"
#include<qcolor.h>

class QLineEdit;
class KColorButton;
class KIconButton;
class QRadioButton;
class QButtonGroup;

/**
* Configuration for basic @ref KMailDrop
* @author Sirtaj Singh Kang (taj@kde.org)
* @version $Id$
*/
class KGeneralCfg : public KMonitorCfg
{
  Q_OBJECT

  public:

    KGeneralCfg(KMailDrop * drop) : KMonitorCfg(drop) {}
    virtual ~KGeneralCfg() {}

    virtual QString name() const;
    virtual QWidget *makeWidget( QWidget *parent );
    virtual void readConfig();
    virtual void updateConfig();

  protected slots:

    void slotDisplayStyleChanged(int);

  private:

    QLineEdit *_caption;

    QButtonGroup *_displayStyleGroup;
    KColorButton *_bg;
    KColorButton *_bgNew;
    KColorButton *_fg;
    KColorButton *_fgNew;
    KIconButton  *_icon;
    KIconButton  *_iconNew;
    QRadioButton *_useColour;
    QRadioButton *_useIcon;

};

#endif // SSK_GENCFG_H
