/*
* pollcfg.h -- Declaration of class KPollCfg.
* Generated by newclass on Mon Aug  3 01:51:07 EST 1998.
*/
#ifndef SSK_POLLCFG_H
#define SSK_POLLCFG_H

#include"moncfg.h"

class QSpinBox;
class KPollableDrop;

/**
* @short KPollCfg
* @author Sirtaj Singh Kang (taj@kde.org)
* @version $Id$
*/
class KPollCfg : public KMonitorCfg
{
public:
	/**
	* KPollCfg Constructor
	*/
	KPollCfg( KPollableDrop *drop );

	/**
	* KPollCfg Destructor
	*/
	virtual ~KPollCfg() {}

	virtual QString name() const;
	virtual QWidget *makeWidget( QWidget *parent );
	virtual void updateConfig();
	
private:
	KPollCfg& operator=( KPollCfg& );
	KPollCfg( const KPollCfg& );

	QSpinBox *_freq;
};

#endif // SSK_POLLCFG_H
