/*
* popcfg.h -- Declaration of class KPopCfg.
* Generated by newclass on Mon Aug  3 14:58:11 EST 1998.
*/
#ifndef SSK_POPCFG_H
#define SSK_POPCFG_H

#include "moncfg.h"

class QLineEdit;
class KPop3Drop;
class QCheckBox;

/**
* Configuration manager for @ref KPop3Drop monitors.
* @author Sirtaj Singh Kang (taj@kde.org)
* @version $Id$
*/
class KPopCfg : public KMonitorCfg
{
public:
	/**
	* KPopCfg Constructor
	*/
	KPopCfg( KPop3Drop *drop );

	/**
	* KPopCfg Destructor
	*/
	virtual ~KPopCfg() {}
	
	virtual QString name() const;
	virtual QWidget *makeWidget( QWidget *parent );
	virtual void updateConfig();

private:
	KPopCfg& operator=( KPopCfg& );
	KPopCfg( const KPopCfg& );

	QLineEdit *_serverEdit;
	QLineEdit *_portEdit;
	QLineEdit *_userEdit;
	QLineEdit *_pwdEdit;
	QCheckBox *_savePass;
	QCheckBox *_apopAuth;
};

#endif // SSK_POPCFG_H
