/*
* typedlg.h -- Declaration of class TypeDialog.
* Generated by newclass on Sun May 10 09:01:23 EST 1998.
*/
#ifndef SSK_TYPEDLG_H
#define SSK_TYPEDLG_H

#include <qdialog.h>
#include <qstring.h>
#include <qstringlist.h>

class QListBox;
class KPushButton;

/**
* Allows selection of a mailbox type
* @author Sirtaj Singh Kang (taj@kde.org)
* @version $Id$
*/
class TypeDialog : public QDialog
{
	Q_OBJECT

private:
	TypeDialog& operator=( TypeDialog& );
	TypeDialog( const TypeDialog& );
	KPushButton *btOk;
	QListBox  *_list;
	QString	_type;
public:
	/**
	* TypeDialog Constructor
	*/
	TypeDialog( const QStringList& types, QWidget *parent = 0,
		 const char *name = 0, bool modal = false );

	QString type() const { return _type; }

public slots:
	void setType( const QString& );
	void select( const QString& );
};

#endif // SSK_TYPEDLG_H
