/*
* unixcfg.h -- Declaration of class KUnixCfg.
* Generated by newclass on Mon Aug  3 02:08:36 EST 1998.
*/
#ifndef SSK_UNIXCFG_H
#define SSK_UNIXCFG_H

#include"moncfg.h"

class KURLRequester;
class KUnixDrop;

/**
* Configuration manager for UNIX mailboxes ( @ref KUnixDrop ).
* @author Sirtaj Singh Kang (taj@kde.org)
* @version $Id$
*/
class KUnixCfg : public KMonitorCfg
{
private:
	KURLRequester *_fileEdit;

public:
	/**
	* KUnixCfg Constructor
	*/
	KUnixCfg( KUnixDrop *drop );

	/**
	* KUnixCfg Destructor
	*/
	virtual ~KUnixCfg(){}

        virtual QString name() const;
        virtual QWidget *makeWidget( QWidget *parent );
        virtual void updateConfig();
 	
private:
	KUnixCfg& operator=( KUnixCfg& );
	KUnixCfg( const KUnixCfg& );
};

#endif // SSK_UNIXCFG_H
