.TH DLPSH 1 "Palm Computing Device Tools" "FSF" \" -*- nroff -*-
.SH NAME
dlpsh \- command shell for executing DLP commands to a Palm Device
.SH SYNOPSIS
.B dlpsh /dev/cua?
.SH DESCRIPTION
This manual page
documents the small application
.BR dlpsh .
.B dlpsh
allows the user to connect to a Pilot and execute arbitrary
.B Data Link Protocol
(DLP) commands to a Pilot connected to the specified callout
device.  Once 
.B dlpsh
is started, the user must invoke HotSync on the target device.
Once connected, the user may execute any of the built-in
.B DLP
commands. (See 
.BR BUILT-IN\ COMMANDS ).
The connection to the Pilot is kept alive by sending a
.B PadTickle
packet to the Pilot after a small period of non-activity. (7 seconds
by default)
.SS BUILT-IN COMMANDS
user [-n username] [-i user id] [-v viewer id] [-p pc id]
.SS OPTIONS
none
.SH USEAGE
The program will connect to a target, and give the user a prompt for
executing commands.
.SH BUGS
.BR dlpsh
has no known bugs.
.SH AUTHOR
.B dlpsh
was written by Chris Stevens and Damien Neil
