.TH INSTALL-USER 1 "Palm Computing Device Tools" "FSF" \" -*- nroff -*-
.SH NAME
install-hinote \- installs a new Hi-Note in a Palm Device
.SH SYNOPSIS
.B install-hinote /dev/cua? filename [filename filename ...]
.SH DESCRIPTION
This manual page
documents the small application
.BR install-hinote .
.B install-hinote
allows the user to write one or more files as a new Hi-Note or Hi-Notes,
respectively, on the Pilot connected to the specified callout
device.  Once 
.B install-hinote
is started, the user must invoke HotSync on the target device.
.SS OPTIONS
none
.SH USEAGE
The program will connect to a target, and write the file or files
given on the command line.
.SH BUGS
The Palm Device may have a maximum length on Hi-Note sizes.
.SH AUTHOR
.B install-hinote
was written by Bill Goodman
