.TH INSTALL-USER 1 "Palm Computing Device Tools" "FSF" \" -*- nroff -*-
.SH NAME
install-memo \- installs a new memo in a Palm Computing Device
.SH SYNOPSIS
.B install-memo 
.RB [ -c 
.IR category
]
.RI -p\  <port>
filename [filename filename ...]
.PP
.SH DESCRIPTION
This manual page
documents the small application
.BR install-memo .
.B install-memo
allows the user to write one or more files as a new memo or memos,
respectively, on the Pilot connected to the specified callout
device.  Once 
.B install-memo
is started, the user must invoke HotSync on the target device.
.SS OPTIONS
.TP
.BI \-c\  category
Install memo(s) to category 
.I category
by default. Normally 
.B install-memo
uses 
.I Unfiled 
as the default category. 
.TP
.B -q
Causes 
.B install-memo
to be quiet and not prompt you to press the HotSync button.
.TP
.B -r
Replace all memos in the category specified by the  
.BI \-c\  category 
option.
.TP
.B -t
Use the filename as the title for the memo. (The title is the first line of 
a memo.)

.SH USEAGE
The program will connect to a target, and write the file or files
given on the command line.
.SH BUGS
The Palm Device may have a maximum length on memo sizes.
.SH AUTHOR
.B install-memo
was written by Damien P. Neil
