.TH INSTALL-USER 1 "Palm Computing Device Tools" "FSF" \" -*- nroff -*-
.SH NAME
install-user \- reads or installs a User Name in a Palm Device
.SH SYNOPSIS
.B install-user /dev/cua? [username]
.SH DESCRIPTION
This manual page
documents the small application
.BR install-user .
.B install-user
allows the user to read or change the User Name on the Pilot connected 
to the specified callout device.  Once executing
.B install-user
the user must invoke HotSync on the target device.
.SS OPTIONS
none
.SH USEAGE
The program will connect to a target, and read install the User Name
given on the command line, or read the User Name if none is specified.
.SH BUGS
.BR install-user
has no known bugs.
.SH AUTHOR
.B install-user
was written by D. Jeff Dionne
