.TH READ-ICAL 1 "Palm Computing Device Tools" "FSF" \" -*- nroff -*-
.SH NAME
read-ical \- coverts information on your Palm Computing Device into 
an Ical-formatted calendar 
.SH SYNOPSIS
.B read-ical /dev/tty[<0..n>] filename
.SH DESCRIPTION
This manual page documents the small application
.BR read-ical .
.B read-ical
allows the user to retrieve the contents of the ToDo and Datebook databases
on a a Pilot, and convert their contents to an Ical calendar.
Once 
.B read-ical
is started, the user must invoke HotSync on the target device.

Note that the calendar file named by
.B filename
will be deleted, so do not use your main calendar. Instead, use
a separate one for this purpose, and include it in your main
calendar.

As 
.B read-ical 
works by passing a script to ical, ical must be in your path.
.SS OPTIONS
<port> <filename>
.SH USEAGE
The program will connect to a target device, retrieve the ToDo and Datebook 
databases (ToDoDB.pdb and DatebookDB.pdb respectively), then instruct
.B ical
to write a calendar file based on the retrieved information.
.SH AUTHOR
.B read-ical
was written by Kenneth Albanowski

