debian/tmp/usr/bin/kalarm
debian/tmp/usr/bin/kalarmd
debian/tmp/usr/share/applications/kde/kalarm.desktop
debian/tmp/usr/share/applnk/.hidden/kalarmd.desktop
debian/tmp/usr/share/applnk/Applications/kalarm.desktop
debian/tmp/usr/share/apps/kalarm
debian/tmp/usr/share/autostart/kalarm.tray.desktop
debian/tmp/usr/share/autostart/kalarmd.autostart.desktop
debian/tmp/usr/share/doc/kde/HTML/en/kalarm
debian/tmp/usr/share/icons/crystalsvg/16x16/actions/kalarm.png
debian/tmp/usr/share/icons/crystalsvg/16x16/apps/kalarm.png
debian/tmp/usr/share/icons/crystalsvg/22x22/actions/kalarm.png
debian/tmp/usr/share/icons/crystalsvg/32x32/apps/kalarm.png
debian/tmp/usr/share/icons/crystalsvg/48x48/apps/kalarm.png
debian/icons/kalarm.xpm /usr/share/pixmaps
debian/icons/kalarm-16.xpm /usr/share/pixmaps
