debian/tmp/usr/include/kde/ksharedfile.h
debian/tmp/usr/include/kde/kitchensync/partbar.h
debian/tmp/usr/include/kde/kitchensync/manipulatorpart.h
debian/tmp/usr/include/kde/kitchensync/systemtray.h
debian/tmp/usr/include/kde/kitchensync/mainwindow.h
debian/tmp/usr/include/kde/kitchensync/profile.h
debian/tmp/usr/lib/libksync2.so
debian/tmp/usr/lib/libksync2.la
debian/tmp/usr/lib/libksharedfile.so
debian/tmp/usr/lib/libksharedfile.la
debian/tmp/usr/lib/libkonnector.so
debian/tmp/usr/lib/libkonnector.la
debian/tmp/usr/lib/libkitchensyncui.so
debian/tmp/usr/lib/libkitchensyncui.la

