debian/tmp/usr/bin/knode
debian/tmp/usr/lib/kde3/kcm_knode.la
debian/tmp/usr/lib/kde3/kcm_knode.so
debian/tmp/usr/lib/kde3/libknodepart.la
debian/tmp/usr/lib/kde3/libknodepart.so
debian/tmp/usr/lib/kde3/libknodepart.so.1
debian/tmp/usr/lib/kde3/libknodepart.so.1.0.0
debian/tmp/usr/lib/libknodecommon.so.0
debian/tmp/usr/lib/libknodecommon.so.0.0.0
debian/tmp/usr/share/applications/kde/KNode.desktop
debian/tmp/usr/share/apps/knode
debian/tmp/usr/share/doc/kde/HTML/en/knode
debian/tmp/usr/share/icons/crystalsvg/128x128/apps/knode.png
debian/tmp/usr/share/icons/crystalsvg/128x128/apps/knode2.png
debian/tmp/usr/share/icons/crystalsvg/16x16/apps/knode.png
debian/tmp/usr/share/icons/crystalsvg/16x16/apps/knode2.png
debian/tmp/usr/share/icons/crystalsvg/32x32/apps/knode.png
debian/tmp/usr/share/icons/crystalsvg/32x32/apps/knode2.png
debian/tmp/usr/share/icons/crystalsvg/48x48/apps/knode.png
debian/tmp/usr/share/icons/crystalsvg/48x48/apps/knode2.png
debian/tmp/usr/share/icons/crystalsvg/64x64/apps/knode.png
debian/tmp/usr/share/icons/crystalsvg/64x64/apps/knode2.png
debian/tmp/usr/share/services/knewsservice.protocol
debian/tmp/usr/share/services/knode_config_*.desktop
debian/icons/knode.xpm /usr/share/pixmaps
debian/icons/knode-16.xpm /usr/share/pixmaps
