debian/tmp/usr/bin/konsolekalendar
debian/tmp/usr/share/applications/kde/konsolekalendar.desktop
debian/tmp/usr/share/doc/kde/HTML/en/konsolekalendar/common
debian/tmp/usr/share/doc/kde/HTML/en/konsolekalendar/index.cache.bz2
debian/tmp/usr/share/doc/kde/HTML/en/konsolekalendar/index.docbook
debian/tmp/usr/share/icons/crystalsvg/16x16/apps/konsolekalendar.png
debian/tmp/usr/share/icons/crystalsvg/22x22/apps/konsolekalendar.png
debian/tmp/usr/share/icons/crystalsvg/32x32/apps/konsolekalendar.png
