######################################################################
# Automatically generated by qmake (2.00a) sö 25. jun 20:59:27 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += conversationdelegate.h \
           dummykonadiadapter.h \
           conversation.h \
           message.h \
           foldermodel.h \
           mailview.h
SOURCES += conversationdelegate.cpp \
           dummykonadiadapter.cpp \
           conversation.cpp \
           message.cpp \
           foldermodel.cpp \
           mailview.cpp \
           main.cpp
