#cmakedefine HAVE_SYS_INOTIFY_H 1

//#define GRANTLEE_PLUGIN_PATH "@Grantlee_PLUGIN_INSTALL_DIR@"
//# workaround
#define GRANTLEE_PLUGIN_PATH "${CMAKE_INSTALL_PREFIX}/${LIB_INSTALL_DIR}"
#define MESSAGEVIEWER_GRANTLEE_PLUGIN_PATH "${CMAKE_INSTALL_PREFIX}/${LIB_INSTALL_DIR}/grantlee/${Grantlee_VERSION_MAJOR}.${Grantlee_VERSION_MINOR}"

