# - Try to find the gnokii directory library
# Once done this will define
#
#  GNOKII_FOUND - system has GNOKII
#  GNOKII_INCLUDE_DIR - the GNOKII include directory
#  GNOKII_LIBRARIES - The libraries needed to use GNOKII

if (GNOKII_INCLUDE_DIR AND GNOKII_LIBRARIES)
  # Already in cache, be silent
  set(GNOKII_FIND_QUIETLY TRUE)
endif (GNOKII_INCLUDE_DIR AND GNOKII_LIBRARIES)

FIND_PATH(GNOKII_INCLUDE_DIR gnokii.h
)

FIND_LIBRARY(GNOKII_LIBRARIES NAMES gnokii
)
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GNOKII DEFAULT_MSG GNOKII_INCLUDE_DIR GNOKII_LIBRARIES )

MARK_AS_ADVANCED(GNOKII_INCLUDE_DIR GNOKII_LIBRARIES)
